# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts that run after cloning repository
install:
  - ps: pushd ..
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/boost_1_61_0-build.7z -OutFile boost.7z
  # - ps: 7z x boost.7z -bso0
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/OpenSSL-1.1.0d-build.7z -OutFile OpenSSL.7z
  # - ps: 7z x OpenSSL.7z -bso0
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/poco-1.7.7-all-build.7z -OutFile poco.7z
  # - ps: 7z x poco.7z -bso0
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/swigwin-3.0.8-build.7z -OutFile swig.7z
  # - ps: 7z x swig.7z -bso0
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/protobuf-3.1.0-build.7z -OutFile protobuf.7z
  # - ps: 7z x protobuf.7z -bso0
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/pgsql-9.6.1-build.7z -OutFile pgsql.7z
  # - ps: 7z x pgsql.7z -bso0
  # - ps: Invoke-WebRequest http://yadoms.com/appveyor_build/gammu-1.38.1-yadoms-build.7z -OutFile gammu.7z
  # - ps: 7z x gammu.7z -bso0
  # - ps: rm *.7z
  - ps: dir
  - ps: popd
  - ps: dir
  - ps: echo [END] install

# scripts to run before build
before_build:
  # Some information
  - ps: echo Current directory = %cd%
  
  # Yadoms configuration file
  - ps: echo Configuring Yadoms CMakeListsUserConfig.txt
  - ps: set "cd_for_cmake=%cd:\=/%"
  - ps: echo set(BOOST_ROOT "%cd_for_cmake%/../boost_1_61_0") > sources/CMakeListsUserConfig.txt
  - ps: echo set(POCO_ROOT "%cd_for_cmake%/../poco-1.7.7-all") >> sources/CMakeListsUserConfig.txt
  - ps: echo set(OPENSSL_ROOT "%cd_for_cmake%/../OpenSSL-1.1.0d") >> sources/CMakeListsUserConfig.txt
  - ps: echo set(PROTOBUF_ROOT "%cd_for_cmake%/../protobuf-3.1.0") >> sources/CMakeListsUserConfig.txt
  - ps: echo set(SWIG_ROOT "%cd_for_cmake%/../swig-3.0.8") >> sources/CMakeListsUserConfig.txt
  - ps: echo set(PostgreSQL_ROOT "%cd_for_cmake%/../pgsql") >> sources/CMakeListsUserConfig.txt
  - ps: echo set(GAMMU_ROOT "%cd_for_cmake%/../gammu") >> sources/CMakeListsUserConfig.txt
  - ps: echo set(COTIRE_USE ON) >> sources/CMakeListsUserConfig.txt
  - ps: echo set(COTIRE_USE_UNITY ON) >> sources/CMakeListsUserConfig.txt
  - ps: echo set(PYTHON_USE_SOURCES OFF) >> sources/CMakeListsUserConfig.txt
  - ps: echo set(PYTHON_ROOT "C:/Python27") >> sources/CMakeListsUserConfig.txt
  
  #TODO virer
  - ps: python --version
  - cmd: dir C:
  
  # Create solution
  - ps: cmake_windows.cmd
  
  
build:
  parallel: true                  # enable MSBuild parallel builds
  project: projects/yadoms.sln    # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: detailed