language: cpp

before_install:
- sudo apt-get install libbz2-dev python-dev

# boost
- wget http://netcologne.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
- tar xjf boost_1_60_0.tar.bz2
- cd boost_1_60_0
- ./bootstrap.sh
- ./b2 --with-atomic --with-chrono --with-date_time --with-filesystem --with-regex --with-thread --with-system link=shared

# poco
- wget http://pocoproject.org/releases/poco-1.7.2/poco-1.7.2.tar.gz
- tar xzf poco-1.7.2-all.tar.gz
- sudo apt-get install libssl-dev
- cd poco-1.7.2-all/
- ./configure --omit=CppUnit,CppUnit/WinTestRunner,Data,Data/SQLite,Data/ODBCData/MySQL,MongoDB,PageCompiler,PageCompiler/File2Page  --no-samples --no-tests
- make
- cd ..

# protobuf
- sudo apt-get install autoconf libtool
- wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
- tar xzf protobuf-2.6.1.tar.gz
- cd protobuf-2.6.1
- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo ldconfig
- cd ..

# libudev
- sudo apt-get install libudev-dev

#gammu
- wget http://dl.cihar.com/gammu/releases/gammu-1.36.8.tar.gz
- tar zxvf gammu-1.36.8.tar.gz
- cd gammu-1.36.8
- mkdir build
- cd build
- cmake .. -DBUILD_SHARED_LIBS=ON
- make
- cd ..
- cd ..


# PCRE
- sudo apt-get install libpcre3 libpcre3-dev

# SWIG
- wget http://prdownloads.sourceforge.net/swig/swig-3.0.8.tar.gz
- tar xzf swig-3.0.8.tar.gz
- cd swig-3.0.8
- ./configure
- make
- sudo make install
- cd ..

# Python
- sudo apt-get install python-dev

# Yadoms configuration file
- echo "set(BOOST_ROOT \"`pwd`/boost_1_60_0\")" >> sources/CMakeListsUserConfig.txt
- echo "set(POCO_ROOT \"`pwd`/poco-.7.2-all\")" >> sources/CMakeListsUserConfig.txt
- echo "SET(COTIRE_USE ON)" >> sources/CMakeListsUserConfig.txt
- echo "set(PROTOBUF_ROOT \"`pwd`/protobuf-2.6.1\")" >> sources/CMakeListsUserConfig.txt
- echo "set(GAMMU_ROOT \"`pwd`/gammu-1.36.8\")" >> sources/CMakeListsUserConfig.txt
- echo "set(SWIG_ROOT \"`pwd`/swig-3.0.8\")" >> sources/CMakeListsUserConfig.txt


# Yadoms
- ./cmake_linux.sh
- cd projects
- make
- cd ..
